
services:
  discord-shots-counter:
    build:
      context: https://github.com/FlorianObermayer/discord-shots-counter.git#main
      dockerfile: Dockerfile
    container_name: discord-shots-counter
    restart: unless-stopped
    ports:
      - "30000-30100:3000"
    environment:
      - NODE_ENV=production
      - APP_ID=${APP_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - DB_PATH=/app/data/database.db
    volumes:
      - ./data:/app/data
      - ./config:/app/config