on:
  push:
    branches:
      - main

jobs:
  call-portainer-webhook:
    name: Call Portainer Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Update Service via Webhook
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
